services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: brochatik-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - brochatik-network
        
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "brochatik-backend"
    ports:
      - "5176:5176"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5176
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
    networks:
      - brochatik-network

  redis:
    image: redis
    container_name: brochatik-redis
    ports:
      - "6379:6379"
    networks:
      - brochatik-network
        

networks:
  brochatik-network:
    driver: bridge
