services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - brochatik-network
    container_name: chat-frontend
        
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5176:5176"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
    networks:
      - brochatik-network
    container_name: chat-backend
        
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - brochatik-network
    container_name: chat-redis
        
networks:
  brochatik-network:
    driver: bridge
